In [1]:
 # importing the libraries
 
 import numpy as np
 import matplotlib.pyplot as plt



In [2]:
# creates a sequence of number from 0 to 14 similar to python range
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
# reshape arranges this into the defined number of rowa and columns
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
# Dsiplays the numbers of roiwvs vs columns
a.shape

(3, 5)

In [5]:
a.size


15

In [6]:
a.dtype

dtype('int32')

In [7]:
type(a)

numpy.ndarray

In [8]:
a[0]

array([0, 1, 2, 3, 4])

In [9]:
a[1]

array([5, 6, 7, 8, 9])

In [10]:
a[2]

array([10, 11, 12, 13, 14])

In [11]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
b=np.array([6,7,8])
type(b)

numpy.ndarray

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
c=np.array([1, 2, 3])
print (c)

[1 2 3]
