In [1]:
# Importing the necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings    # importing python warning module
sns.set_theme()            #setting seaborn as default style for plots when using matplotlib

# Assignment 5 
## Risk

Write a program (or notebook) called assignment_5_risk (.py or .ipynb)

The program should simulates 1000 individual battle rounds in Risk (3 attacker vs 2 defender) and plots the result.

One battle round is one shake of the attacker and defender dice.

I am being vague about what it plot, I will leave that to you.

For the last few marks.

A more complicated version simulates a full series of rounds for armies of arbitrary sizes, until one side is wiped out,

and plots the results.

(This is open ended, so it is only for the last few marks)

## Risk Strategy notes
- Mission: To conquer all the territories
- Players: Army A (Attacker) vs Army B
- Dice: 6 sided dice
- One round: Attacker rolls the dice 3 times and the defender rolls the dice 2 times.
- Dice compared per round: 
  - Total dice rolled (5): Sum of attacker (3) vs defenders (2) dice rolled
   - Sort all 5 dice rolled from highest to lowest (descending order)
   - Compare attackers highest 2 dice rolls vs defenders 2 dice rolls
- Winning Rules:
 1. Compare the highest dice first and determine winner for the first dice;
   - Attacker loses one troop when each dice roll is ≤ defenders dice roll. 
   - Defender loses one troop when attackers dice roll is > defenders
 2. Compare the second highest dice next and determine winner for the second dice: 
  - Attacker loses one troop when each dice roll is ≤ defenders dice roll. 
  - Defender loses one troop when attackers dice roll is > defenders
= Task: Simulate 1000 individual battle rounds in Risk (3 attacker vs 2 defender) and plot the result.

         



## Simulating the risk game battle approach
A combination of codes and functions were utilized to handle this task and the steps involved in building up this function are in the cells below. This approach was used to offer simplicity and easy debugging of the codes when run in simpler blocks before integrating all into a function. The aricle by Stephen Gruppetta on using Python’s NumPy To Improve Your Board Game Strategy: Your Odds When Attacking in ‘Risk’ was very helpful in tackling this assignment and it can be found [here](https://thepythoncodingbook.com/2022/12/30/using-python-numpy-to-improve-board-game-strategy-risk/)

In [2]:
# Define the number of battle rounds
n_rolls = 1000 # 1000 battle rounds

In [3]:
# Defining a function for 6-sided dice rolls Risk Game
def dice_rolls():

    # simulating risk game play using numpy random numbers generator with  a 6-sided dice rolls per attack 
    attacker = np.random.randint(1, 7, (n_rolls, 3))  # number of battle rounds, attacker rolls 3 dice per attack
    defender = np.random.randint(1, 7, (n_rolls, 2))  # number of battle rounds, defender rolls 2 dice dice per attack

    #Sort the rolls in descending order
    attacker_sorted = np.sort(attacker, axis=1)[:, ::-1]
    defender_sorted = np.sort(defender, axis=1)[:, ::-1]

    



In [4]:
#  Define the number of battle rounds
n_rolls = 1000 # 1000 battle rounds

In [5]:
# simulating risk game play using numpy random numbers generator with  a 6-sided dice rolls per attack 

attacker = np.random.randint(1, 7, (n_rolls, 3))  # number of battle rounds, attacker rolls 3 dice per attack
defender = np.random.randint(1, 7, (n_rolls, 2))  # number of battle rounds, defender rolls 2 dice dice per attack
print (attacker)

[[1 2 4]
 [4 2 3]
 [5 4 4]
 ...
 [5 1 6]
 [3 3 2]
 [1 1 6]]


In [6]:
print (defender)

[[2 6]
 [1 2]
 [3 6]
 ...
 [3 6]
 [1 3]
 [3 5]]


In [7]:
 #Sort the rolls in descending order
attacker_sorted = np.sort(attacker, axis=1)[:, ::-1]
defender_sorted = np.sort(defender, axis=1)[:, ::-1]
print (attacker_sorted)

[[4 2 1]
 [4 3 2]
 [5 4 4]
 ...
 [6 5 1]
 [3 3 2]
 [6 1 1]]


In [8]:
print (defender_sorted)

[[6 2]
 [2 1]
 [6 3]
 ...
 [6 3]
 [3 1]
 [5 3]]


In [9]:



# Defining a function for 6-sided dice rolls per attack
def dice_rolls():
    attacker = np.random.randint(1, 7, 3)  # Attacker rolls 3 dice
    defender = np.random.randint(1, 7, 2)  # Defender rolls 2 dice
    
    # Sort the rolls in descending order
    attacker_sorted = np.sort(attacker)[::-1]
    defender_sorted = np.sort(defender)[::-1]
    
    return attacker_sorted, defender_sorted

In [10]:
# Removing the unused dice rolls from the attacker to equate defenders' dice roll



In [11]:

def dice_rolls():
    attacker = np.random.randint(1, 7, 3) # generates a random integer in the range of 1 to 6, attacker rolls 3 times
    defender = np.random.randint(1, 7, 2) # generates a random integer in the range of 1 to 6, defender rolls 2 times
    attacker_sorted = sorted(attacker, reverse=True)  # reverse=true converts this to a python slicing function
    defender_sorted = sorted(defender, reverse=True)
    return attacker_sorted, defender_sorted
sorted_desc = np.sort(arr)[::-1] 



NameError: name 'arr' is not defined

In [ ]:
# number of rolls
n = 1000

In [ ]:
# number of rolls
n = 1000

## References
- https://www.w3schools.com/python/numpy/numpy_random.asp
- https://prepfortech.io/leetcode-solutions/dice-roll-simulation
- https://thepythoncodingbook.com/2022/12/30/using-python-numpy-to-improve-board-game-strategy-risk/
- https://datascienceparichay.com/article/sort-numpy-array-in-descending-order/
- https://sqlpey.com/python/numpy-array-sorting/
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html